# Generated by Django 3.0.4 on 2020-04-23 18:38

import django.contrib.auth.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_delete_user'),
        ('authorization', '0002_auto_20200423_2317'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='liked',
        ),
        migrations.AddField(
            model_name='user',
            name='liked',
            field=models.ManyToManyField(related_name='liked_products', to='api.Product'),
        ),
        migrations.RemoveField(
            model_name='user',
            name='myOrders',
        ),
        migrations.AddField(
            model_name='user',
            name='myOrders',
            field=models.ManyToManyField(related_name='bought_products', to='api.Product'),
        ),
        migrations.AlterField(
            model_name='user',
            name='password',
            field=models.CharField(max_length=128, verbose_name='password'),
        ),
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username'),
        ),
    ]
